name: Polka Codes Issues Handler

on:
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: number

permissions:
  contents: write # required for push commit
  pull-requests: write # required for create pr

concurrency:
  group: issue-${{ github.event.issue.number || github.event.inputs.issue_number }}
  cancel-in-progress: true

jobs:
  handle:
    timeout-minutes: 10
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'polka.codes')) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Process issue
        id: process
        uses: polka-codes/action@master
        with:
          github_token: ${{ github.token }}
          issue_number: ${{ github.event.issue.number || github.event.inputs.issue_number }}

      

      - name: Run polka.codes CLI and create PR
        env:
          POLKA_API_PROVIDER: ${{ vars.PROVIDER }}
          POLKA_MODEL: ${{ vars.MODEL }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "$TASK" | pokla -v --budget 1
          POLKA_API_PROVIDER=openrouter POLKA_MODEL=deepseek/deepseek-chat pokla commit -a
          git push origin polka-codes/issue-$ISSUE_NUMBER
          POLKA_API_PROVIDER=openrouter POLKA_MODEL=deepseek/deepseek-chat pokla pr "closes #$ISSUE_NUMBER"

# Generated by polka.codes
